service: send-sms-serverless
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-west-2
  iamRoleStatements:
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "sns:*"

  environment:
    PUBLISHED_MESSAGE_DETAILS_SNS_ARN: ${ssm:published-message-details-sns-arn}
    SEND_SMS_SNS_ARN: ${ssm:send-sms-sns-arn}
    PUBLISHED_MESSAGE_DETAILS_SQS_ARN: ${ssm:published-message-details-sqs-arn}
    PUBLISHED_MESSAGE_DETAILS_SQS_URL: ${ssm:published-message-details-sqs-url}

functions:
  publishMessageDetailsToSns:
    handler: src/publishMessageDetailsToSnsHandler.handler
    events:
      - http:
          path: /publish-message-details
          method: post

  sendSms:
    handler: src/sendSmsHandler.handler
    events:
      - sqs: ${self:provider.environment.PUBLISHED_MESSAGE_DETAILS_SQS_ARN}

resources:
  Resources:
    SNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: PublishedMessageDetailsSNSTopic

    SNSTopicSendSms:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: SendSmsSNSTopic

    SQSQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: PublishedMessageDetailsSQSQueue

    SNSTopicQueuePolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        Queues:
          - ${self:provider.environment.PUBLISHED_MESSAGE_DETAILS_SQS_URL}
        PolicyDocument:
          Statement:
            - Sid: "allow-sns-messages"
              Effect: Allow
              Resource: ${self:provider.environment.PUBLISHED_MESSAGE_DETAILS_SQS_ARN}
              Action:
                - "SQS:SendMessage"
              Principal:
                Service:
                  - sns.amazonaws.com
              Condition:
                ArnEquals:
                  "aws:SourceArn": ${self:provider.environment.PUBLISHED_MESSAGE_DETAILS_SNS_ARN}

    SQSQueueSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        TopicArn: ${self:provider.environment.PUBLISHED_MESSAGE_DETAILS_SNS_ARN}
        Endpoint: ${self:provider.environment.PUBLISHED_MESSAGE_DETAILS_SQS_ARN}
        Protocol: sqs
        RawMessageDelivery: true
